# SPDX-FileCopyrightText: Jan Altenberg <jan.altenberg@osadl.org>
#
# SPDX-License-Identifier: CC0-1.0

name: spdx/tools-java conversion workflow
env:
  SPDX_TOOLS_VERSION: 2.0.2
on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
jobs:
  syntax-check-and-conversion-of-tag-value:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
        if: github.event.pull_request.merged == true

      - name: "bootstrap spdx/tools-java"
        run: .github/workflows/scripts/spdx-tools-java-wrapper.sh bootstrap
        if: github.event.pull_request.merged == true

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.1
        with:
          fetch_depth: 50
          files: |
            **/*.spdx
            **/*.spdx.gz
        if: github.event.pull_request.merged == true

      - name: "Verify touched tag-value documents"
        run: .github/workflows/scripts/verify.sh ${{ steps.changed-files.outputs.all_changed_files }}
        if: github.event.pull_request.merged == true

      - name: "Convert touched tag-value documents to JSON, YAML and RDF"
        run: .github/workflows/scripts/convert.sh ${{ steps.changed-files.outputs.all_changed_files }}
        if: github.event.pull_request.merged == true

      - uses: EndBug/add-and-commit@v9
        with:
          add: "['analysed-packages/', '.verifications/']"
          message: "Auto generated by GitHub Action with SPDX Java Tools version ${{ env.SPDX_TOOLS_VERSION }}"
          committer_name: GitHub Actions
          committer_email: actions@github.com
          pull: --rebase --autostash origin main
          push: origin HEAD:main
        if: github.event.pull_request.merged == true

