# SPDX-FileCopyrightText: Maximilian Huber <maximilian.huber@tngtech.com>
# SPDX-FileCopyrightText: Helio Chissini de Castro <heliocastro@gmail.com>
# SPDX-FileCopyrightText: Jan Altenberg <jan.altenberg@osadl.org>
#
# SPDX-License-Identifier: CC0-1.0

name: spdx/tools-java workflow
env:
  SPDX_TOOLS_VERSION: 2.0.2
on:
  pull_request:
    branches:
      - main
jobs:
  syntax-check-of-tag-value:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Bootstrapping spdx/tools-java"
        run: .github/workflows/scripts/spdx-tools-java-wrapper.sh bootstrap

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.1
        with:
          files: |
            **/*.spdx

      - name: "Verify touched tag-value documents with spdx-tools-java"
        run: .github/workflows/scripts/verify.sh ${{ steps.changed-files.outputs.all_changed_files }}
        if: github.event_name == 'pull_request'

      # We do a dummy conversion here, since the Convert function
      # sometimes uncovers syntax errors missed by the Verify function
      - name: "Convert touched tag-value documents"
        run: .github/workflows/scripts/convert.sh ${{ steps.changed-files.outputs.all_changed_files }}
        if: github.event_name == 'pull_request'

